---
- name: Create pods using deployment 
  hosts: kubernetes 
#  become: true
#  user: root
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
 
  tasks: 
  - name: create a deployment
    command: kubectl create -f /home/admin/kubernetes/deploy.yaml
 
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/qhmagento-deploy
