apiVersion: v1
kind: Service
metadata:
  name: qhmagento-service
  labels:
    app: qhmagento
spec:
  selector:
    app: qhmagento
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31200
